{% set version = "1.2.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tidyselect
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidyselect_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidyselect/tidyselect_{{ version }}.tar.gz
  sha256: 169e97ba0bbfbcdf4a80534322751f87a04370310c40e27f04aac6525d45903c

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-cli >=3.3.0              # [build_platform != target_platform]
    - r-glue >=1.3.0             # [build_platform != target_platform]
    - r-lifecycle >=1.0.3        # [build_platform != target_platform]
    - r-rlang >=1.0.4            # [build_platform != target_platform]
    - r-vctrs >=0.5.2            # [build_platform != target_platform]
    - r-withr                    # [build_platform != target_platform]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-cli >=3.3.0
    - r-glue >=1.3.0
    - r-lifecycle >=1.0.3
    - r-rlang >=1.0.4
    - r-vctrs >=0.5.2
    - r-withr
  run:
    - r-base
    - r-cli >=3.3.0
    - r-glue >=1.3.0
    - r-lifecycle >=1.0.3
    - r-rlang >=1.0.4
    - r-vctrs >=0.5.2
    - r-withr

test:
  commands:
    - $R -e "library('tidyselect')"           # [not win]
    - "\"%R%\" -e \"library('tidyselect')\""  # [win]

about:
  home: https://tidyselect.r-lib.org, https://github.com/r-lib/tidyselect
  license: MIT
  summary: A backend for the selecting functions of the 'tidyverse'. It makes it easy to implement select-like functions in your own packages in a way that is consistent with other 'tidyverse' interfaces for selection.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
