# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "rmgayVxslBQCMrkFf52J7YdqZ8Jz4VOx0p1/ktL7meg4SbMjBTq63wPqZg3jY6Mg2PF7xkdlDM9dEcbyYhgpPhb3Mxc9xfPQKWVVKGUhceK7Y/IV07lH6IhwdOoAhxkYECzatX0kap0+k3EW1cL2UTlqFBBgXy2+GeYMX07jNp6uYc4yuV9Y8NSDc2xovml6ld0Kgz6M+SIzKa3mt0iJYVt38F51Cg/OnnOP9B5OdZ9HNyJ+uRxajYFaZhVQi//UsxSBC6Gxzw4IyXteIpxHqvpbps2eLDyyPH2TLSnXkBU9zrZA/HD6iSgsw8aC0jLUmclnEgs3VkcBz2E8fkLiNW0iiQs24UZMwo5Zr52ZoobmiwzFHWSny1ImYvZeZja12j5IlfDz44rhZv+5VqC1WN6m4y3X+yVO3aZUKq1K6/2GWcua3pChAYEiRqVgXBwu63CMWsHKQB7OOntrKqiutCiEEPmpDCcGU3CUu9npOAeldqndj7o6vVIXJw7aUqLlAz8cshrhGKdXes7vCJl2nz3mLabPZPMMg67bO51Rd+gw+w55Usd1uYPAOf334+TSZgkwTathu+V1IDF7M9lUHR/BUGNJONHUdlEK/D5L5nO5KSzku9eqIfloOHQvEKevGC4ykrEmqsekIe4wmMhA3a2/MNw0jgY05gIVKxNhzM0="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_r_base3.5.1target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

    - env: CONFIG=linux_ppc64le_r_base3.6target_platformlinux-ppc64le UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux-ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi